---
# Source: jenkins/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/managed-by": ""
    "app.kubernetes.io/instance": "local"
    "app.kubernetes.io/component": "jenkins-controller"
type: Opaque
data:
  jenkins-admin-password: "OHF2MWxUeHJ1aXMxU0FpUko0NU1tbw=="
  jenkins-admin-user: "YWRtaW4="
